version: "2"

services:
  elasticsearch:
    image: elasticsearch:5.2.0
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - elk

  logstash:
    image: logstash:5.2.0
    ports:
      - 9998:9998
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - elk
    env_file: config/logstash.conf

  kibana:
    image: kibana:5.2.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - elk
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

networks:
  elk:
